OPHAKTKEH-139 Add API to create, update and delete meeting dates.
Opetushallitus/akt pull request #118
Opened 2022-02-07 14:38 UTC by terova

2022-02-08 12:00 UTC, mikhuttu commented on src/main/java/fi/oph/akt/service/MeetingDateService.java
> +    final MeetingDate meetingDate = meetingDateRepository.getById(dto.id());
Tänne sekä deleten alle voisi myös miettiä `findById` ratkaisua. Käyn muuten tän pull requestin läpi myöhemmin.

2022-02-08 12:01 UTC, mikhuttu commented on src/main/java/fi/oph/akt/service/MeetingDateService.java
> +    }
Tää taitaa olla poistuva jäänne?

2022-02-08 13:39 UTC, terova commented on src/main/java/fi/oph/akt/service/MeetingDateService.java
> +    }
No hups. Pitäisikö lisätä testi, kuten monesti aiemmissa projekteissa, joka feilaa jos lähdekoodissa on System.out.

2022-02-08 15:02 UTC, mikhuttu commented on src/main/java/fi/oph/akt/service/MeetingDateService.java
> +    }
Jos helppo yleiseksi testiksi lisätä, niin hyvin voi laittaa

2022-02-09 13:53 UTC, mikhuttu requested changes
Katsoin läpi ja hyvältä näyttää. Muutamia kommentteja alla ennen mergausta.

2022-02-09 13:53 UTC, mikhuttu commented on src/main/java/fi/oph/akt/api/clerk/MeetingDateController.java
> +import org.springframework.http.MediaType;
Ei tarvetta tälle importille

2022-02-09 13:53 UTC, mikhuttu commented on src/main/java/fi/oph/akt/api/clerk/MeetingDateController.java
> +@RequestMapping(value = "/api/v1/clerk/meetingdate", produces = MediaType.APPLICATION_JSON_VALUE)
Ehkä /meetingDate /meetingdate sijaan?

2022-02-09 13:53 UTC, mikhuttu commented on src/main/java/fi/oph/akt/api/clerk/MeetingDateController.java
> +  private static final String TAG_MEETING_DAY = "Meeting date API";
TAG_MEETING_DATE ?

2022-02-09 13:53 UTC, mikhuttu commented on src/main/java/fi/oph/akt/api/clerk/MeetingDateController.java
> +  @DeleteMapping(path = "/{meetingDayId:\\d+}")
meetingDayId --> meetingDateId

2022-02-09 13:53 UTC, mikhuttu commented on src/main/java/fi/oph/akt/api/clerk/modify/MeetingDateCreateDTO.java
> +package fi.oph.akt.api.clerk.modify;
Pitäisikö siirtää api.dto.clerk.modify pakkauksen alle? Samoin MeetingDateUpdateDTO.

2022-02-09 13:53 UTC, mikhuttu commented on src/main/java/fi/oph/akt/service/MeetingDateService.java
> +      throw new RuntimeException("Can not delete meeting date with authorisations");
Olisiko hyvä heittä vast. exception myös jos tehdään update kokouspäivälle, jolla jo auktorisointeja?

2022-02-09 13:53 UTC, mikhuttu commented on src/test/java/fi/oph/akt/service/MeetingDateServiceTest.java
> +  MeetingDateRepository meetingDateRepository;
Voi lisätä private määreen tänne vaikka ei tarvinne

2022-02-09 15:40 UTC, terova commented on src/main/java/fi/oph/akt/service/MeetingDateService.java
> +      throw new RuntimeException("Can not delete meeting date with authorisations");
Ajattelin ensin että miksi ei voisi muokata, mutta ehkä se on pienemmän riesan tie, kokouspäivien ja alkupäivän suhde on nyt epäselvä. Helpostihan sen rajoitteen saa pois.

2022-02-09 17:21 UTC, mikhuttu approved these changes

2022-02-09 19:31 UTC, merged