OPHAKTKEH-304 Error codes for translator operations
Opetushallitus/akt pull request #201
Opened 2022-03-24 08:21 UTC by terova

2022-03-24 12:00 UTC, p3j4m commented on src/main/java/fi/oph/akt/util/exception/APIExceptionType.java
> +  TRANSLATOR_UPDATE_DUPLICATE_IDENTITY_NUMBER,
Noiden eteen voisi laittaa CLERK prefiksin, vaikka julkisella puolella niitä ei pysty tekemäänkin. Yhtenevämpi kuitenkin muiden käsitteiden kanssa

2022-03-24 15:48 UTC, terova commented on src/main/java/fi/oph/akt/util/exception/APIExceptionType.java
> +  TRANSLATOR_UPDATE_DUPLICATE_IDENTITY_NUMBER,
Sehän tulisi sitten näihin kaikkiin.

2022-03-24 17:07 UTC, p3j4m commented on src/main/java/fi/oph/akt/util/exception/APIExceptionType.java
> +  TRANSLATOR_UPDATE_DUPLICATE_IDENTITY_NUMBER,
Kyllä. Tällä hetkellä on `public translator` ja `clerk translator`, mutta pelkkä translatoria ei ole käytetty muistaakseni.

2022-03-29 12:19 UTC, mikhuttu commented on src/main/reactjs/src/enums/api.ts
> +  AuthorisationDeleteLastAuthorisation = 'authorisationDeleteLastAuthorisation',
Auktorisoinnin poistologiikkaan liittyen voisi lisätä myös palvelimen virheeseen liittyvän error toastin näyttämisen. Saman voinee tehdä myös julkaisuluvan muokkausrajapinnan osalta, vaikka backend ei siihen liittyen APIException-tyyppiseen virheeseen liittyvää vastausta palautakaan.

2022-03-30 07:13 UTC, mikhuttu commented on src/main/reactjs/src/redux/sagas/clerkTranslatorOverview.ts
> -      'akt.component.clerkTranslatorOverview.authorisations.actions.removal.toasts.error'
Tän lokalisaation voi ainakin vielä poistaa. Katson tarkemmin tän PR:n muutoin tänään vielä mut hyvältä näyttää päällisin puolin.

2022-03-30 12:09 UTC, mikhuttu commented on src/main/java/fi/oph/akt/util/exception/APIExceptionType.java
> +  AUTHORISATION_DELETE_LAST_AUTHORISATION;
Itsellä ei suurempaa näkemystä tuon etuliitteen puolesta (ei ehkä tarvetta sille?) , mutta sellaista pohdin että olisiko nämä enumit olla hyvät olla aakkosjärjestyksessä niin täällä, frontendin APIError enumissa kuin translation.jsonissakin? Lähinnä kai tuolla lokalisaatioissa on haluttu pitää lokalisaatiot järejstyksessä ja jos niin tekisi myös näiden virheiden osalta, olisi helppo nähdä että kaikia virheitä vastaa lokalisaatiot jos ne olisi järjestetty samalla lailla APIError enumin alla.

2022-03-30 12:30 UTC, mikhuttu commented
`ClerkNewTranslatorPage.tsx`:n rivit 80-85 sekä lokalisaation `clerkNewTranslatorPage.toasts.error` voi nähdäkseni poistaa

2022-03-30 12:32 UTC, mikhuttu requested changes
Backend-puoli näytti hyvältä ja fronttiinkaan liittyen en huomannut oheisten seikkojen ohella kummempaa kommentoitavaa. Lähinnä jos haluaa tämän taskin yhteydessä niitä tehdä, niin cypress-testejä voi kai kirjoitella. Tai sitten mergataan tällaisenaan ja tehdään noita testejä myöhemmin jos tarvis.

2022-03-30 13:50 UTC, merged