OPHAKTKEH-76 Kääntäjien hakeminen redux-tilaan
Opetushallitus/akt pull request #29
Opened 2021-11-26 10:09 UTC by pkoivisto

2021-12-01 07:34 UTC, p3j4m commented on src/main/reactjs/src/api.ts
> +};
Tätä ei enää tarvita. Tässä pystyisi käyttämään uutta axiosInstancea.

Voidaan oletuksena käyttää nimeä axiosInstance, jotta ei menisi muiden client-kirjastojen kanssa sekaisin.

API-osoitteita varten voisi tehdä enumin enumsin alle.

`import axiosInstance from 'configs/axios';`

2021-12-01 07:35 UTC, p3j4m commented on src/main/reactjs/src/components/elements/ProgressIndicator.tsx
> +);
Hyvä, palataan vielä tähän taskin OPHAKTKEH-92 yhteydessä.

2021-12-01 07:41 UTC, pkoivisto commented on src/main/reactjs/src/api.ts
> +};
Totta, muutan.

2021-12-01 08:14 UTC, p3j4m commented on src/main/reactjs/src/pages/HomePage.tsx
> +    dispatch({ type: 'TRANSLATOR_DETAILS/LOAD' });
Voisi laittaa kaikki actiontypes redux/actionTypes/ alle. Tällä tavalla vältetään typoja. Esim.

export const TRANSLATOR_DETAIL_LOAD = 'TRANSLATOR_DETAILS/LOAD'

....

2021-12-01 08:51 UTC, pkoivisto commented on src/main/reactjs/src/pages/HomePage.tsx
> +    dispatch({ type: 'TRANSLATOR_DETAILS/LOAD' });
Muutettu.

2021-12-01 11:08 UTC, p3j4m commented on src/main/reactjs/src/components/translators/TranslatorListing.tsx
> +    case 'NOT_LOADED':
Nämäkin tulevat muuttumaan taskin OPHAKTKEH-92 yhteydessä, mutta pitäisikö laittaa kuitenkin casejen stringit enumeen?

2021-12-01 11:11 UTC, pkoivisto commented on src/main/reactjs/src/components/translators/TranslatorListing.tsx
> +    case 'NOT_LOADED':
Tällä hetkellä noi on `interfaces/api.ts` löytyvän ApiResponseStatus tyypin mukaisia, mutta enum voi olla parempi.

2021-12-01 11:24 UTC, p3j4m commented on src/main/reactjs/src/pages/HomePage.tsx
> +    dispatch({ type: TRANSLATOR_DETAILS_LOAD });
Tässä voidaan alkaa käyttämään actioneja, eli uusi redux/actions/translatiorin alle funktio, joka palauttaa 

const fetchTranslatorDetails = {
  type: 'TRANSLATOR_DETAILS_LOAD',
}

2021-12-01 11:28 UTC, p3j4m commented on src/main/reactjs/src/redux/reducers/translators/translatorDetails.ts
> +      return { status: 'ERROR', allTranslators: [] };
Näissäkin voisi käyttää ApiResponseStatus enumta.

2021-12-01 11:30 UTC, pkoivisto commented on src/main/reactjs/src/redux/reducers/translators/translatorDetails.ts
> +      return { status: 'ERROR', allTranslators: [] };
Fiksasin, toi jäi vahingossa pois aiemmin.

2021-12-01 11:36 UTC, pkoivisto commented on src/main/reactjs/src/pages/HomePage.tsx
> +    dispatch({ type: TRANSLATOR_DETAILS_LOAD });
Jep, action creatorit tosiaan taitaa olla aika laajasti hyväksytty käytäntö. Mä en enää tämän viikon puolella ehdi tätä muutosta tekemään; saa mun puolesta muuttaa tähän tai sitten voidaan tehdä muutos myöhemmin.

2021-12-01 11:58 UTC, mikhuttu commented on src/main/reactjs/src/interfaces/translator.ts
> +    { fromLang: string; toLang: string; permissionToPublish: boolean }
`permissionToPublish` elementti on poistettu julkisessa listauksessa `languagePairs` taulukon elementeistä. Se löytyy kuitenkin virkailijapuolelta, joka ei liittyne tähän lainkaan.

2021-12-01 12:06 UTC, mikhuttu commented on src/main/reactjs/src/redux/sagas/TranslatorDetails.ts
> +  });
Tää osa periaatteessa turha jatkossa, mutta voidaan toki käyttää frontissa `from` ja `to` kenttiä "mistä - mihin" kieliä määrittämään. Ihan tarpeeksi selkeät näinkin.

2021-12-01 12:08 UTC, mikhuttu commented on src/main/reactjs/src/tests/jest/redux/sagas/TranslatorDetails.test.ts
> +      { fromLang: 'fi', toLang: 'sv', permissionToPublish: true },
Täältä voidaan myös `permissionToPublish` poistaa, vaikka ei tarpeen.

2021-12-01 12:09 UTC, mikhuttu reviewed
Katsoin pikaisesti muutoksia täältä Githubin UI:n kautta läpi ilman että oisin pullannut branchin lokaalisti ja testannut. Mutta mun silmään vaikuttivat noin yleensä hyviltä.

2021-12-01 13:14 UTC, p3j4m commented on src/main/reactjs/src/interfaces/translator.ts
> +    { fromLang: string; toLang: string; permissionToPublish: boolean }
Kyllä, sitä ei tarvita. Poistettu.

2021-12-02 14:02 UTC, mikhuttu requested changes
Hyvältä näyttää! Jätin pieniä muutosehdotuksia alle ja ne voi nyt ainaskin korjata. Noiden lisäksi voisi tosin harkita, että tekisi vielä uudelleennimentöjä koodissa tyyliilä `TranslatorDetails` --> `PublicTranslator` (ja mahd. `LanguagePair` --> `PublicLanguagePair`), `APiEndpoints.PublicTranslatorDetails` --> `APIEndpoints.PublicTranslatorList` jne. TranslatorDetails kuulostaa samalta kuin backendin tällä hetkellä vain virkailijan kääntäjien listauksessa palauttama `details` kenttä jokaista kääntäjää kohti, joka sisältää kääntäjän yhteystiedot, kun taas sen muut tiedot ovat juurielementissä (id, oid). Backendin puolellakin voitaisiin tarvitaessa jättää tuo kenttä pois ja palauttaa yhteystiedot id:n ja oid:n ohella juurielementin kentissä.

Näitä uudelleennimeämisiä voi toisaalta miettiä tehtävän erillisenä taskina tän branchin mergattuakin.

2021-12-02 14:02 UTC, mikhuttu commented on src/main/reactjs/public/i18n/fi-FI.json
> +        "hometown": "Asuinkunta",
Voisi muuttaa olevaan `town`

2021-12-02 14:02 UTC, mikhuttu commented on src/main/reactjs/public/i18n/fi-FI.json
> +        "description": "Auktorisoitujen kääntäjien tutkintolautakunta ylläpitää rekisteriä auktorisoiduista kääntäjistä. Hakukoneella voit hakea kääntäjiä joko nimen tai käännöskielen mukaan. Hakutul
Tätä tekstiä pitänee jollain lailla muuttaa, mutta voidaan katsoa sitä myöhemmin.

2021-12-02 14:02 UTC, mikhuttu commented on src/main/reactjs/src/redux/sagas/translatorDetails.ts
> +    console.log('Loading');
Voi poistaa

2021-12-02 14:02 UTC, mikhuttu commented on src/main/reactjs/src/tests/jest/redux/sagas/translatorDetails.test.ts
> +describe('Saga:TranslatorDetails', () => {
TranslatorDetails pienellä?

2021-12-02 14:02 UTC, mikhuttu commented on src/main/reactjs/src/tests/jest/redux/sagas/translatorDetails.test.ts
> +  it('should invole an ERROR action in case of API fails', async () => {
invole --> invoke

2021-12-02 14:02 UTC, mikhuttu commented on src/main/reactjs/src/tests/jest/redux/sagas/translatorDetails.test.ts
> +    const dispatched: DispatchAction[] = [];
Tän voisi siirtää sekä tässä että alemmassa testissä `await dispatchSaga(...` päälle.

2021-12-02 14:02 UTC, mikhuttu commented on src/main/reactjs/public/i18n/fi-FI.json
> +          "sv": "Ruotsi"
suomi ja ruotsi pienellä

2021-12-02 14:06 UTC, mikhuttu commented
Lisäksi voit vaihtaa Nimi <--> Kieliparit sarakkeet päittäin.

2021-12-02 14:22 UTC, mikhuttu commented on src/main/reactjs/src/components/translators/TranslatorListing.tsx
> +        <Text>{`${firstName} ${lastName}`}</Text>
Nimen voisi siirtää vasemmanpuoleiseksi sarakkeeksi ja muodossa `lastName firstName`

2021-12-02 14:32 UTC, mikhuttu commented
Korjasin yo. commitissa mainitsemani pikkuasiat. Uudelleenimentöjä koodiin voisi toki harkita mutta muuten tä on musta ok mergattavaksi ja voin hyväksyä, jos jätetään nuo nimeämismuutokset myöhemmällä / harkitaan niiden tekemistä tarvittaessa kun virkailija-ui:ta aletaan toteuttaa.

2021-12-02 14:32 UTC, mikhuttu approved these changes

2021-12-03 10:09 UTC, mikhuttu approved these changes
Hyvältä vaikuttaa 👍

2021-12-03 10:10 UTC, merged