OPHAKTKEH-114 Save emails to database and send emails in scheduled task
Opetushallitus/akt pull request #53
Opened 2021-12-16 08:18 UTC by terova

Testejä puuttuu, alustavaan tarkasteluun.

2021-12-20 14:25 UTC, mikhuttu requested changes
Toteutus erittäin jees 👍  Pieniä huomioita tein koodin pohjalta miten sitä voisi parantaa ja niistä kommentteja alla. Testejä en ole vielä ehtinyt kattella ja laitan niistä kommentit myöhemmin.

2021-12-20 14:25 UTC, mikhuttu commented on src/main/resources/db/changelog/db.changelog-1.0.xml
> +    <changeSet id="2021-12-15-create-shedlock-table" author="terova">
Id:hen vois mahdollisesti vaihtaa pvm. osaan päiväksi 15 --> 17 (tai 20:een miolemmissa). Näin olisi ajallisesti loogisesti edeltävän changeSetin jälkeen.

2021-12-20 14:25 UTC, mikhuttu commented on src/main/java/fi/oph/akt/service/email/EmailService.java
> +	public Long saveEmail(final EmailData emailData) {
Kutsu tähän lisätään varmaan ContactRequestServiceen. Pitäisikö tehdä omana taskinaan tän mergaamisen jälkeen?

2021-12-20 14:25 UTC, mikhuttu commented on src/main/resources/db/changelog/db.changelog-1.0.xml
> +            <column name="email_type" type="VARCHAR(255)">
Tän voisi halutessa asettaa `deleted_at` ja `sender` sarakkeiden väliin, kun myös `authorisation` taulussa `basis` ja muut foreign keyt siellä. Jos teet tällaisen muutoksen niin myös Email.class modelissa voi `emailTypen` siirtää ylemmäs.

2021-12-20 14:25 UTC, mikhuttu commented on src/main/resources/db/changelog/db.changelog-1.0.xml
> +                <constraints nullable="false" primaryKey="true"/>
Taitaa olla ekvivalenttia tämän kanssa, mutta vaihdettaisko johdonmukaisuuden puolesta muotoon
`<constraints primaryKey="true" primaryKeyName="shedlock_pkey"/>`

2021-12-20 14:25 UTC, mikhuttu commented on src/main/resources/db/changelog/db.changelog-1.0.xml
> +            <column name="locked_at" type="TIMESTAMP">
Nämä aikaleimat taitavat olla tarkoituksella tyyppiä `TIMESTAMP` kun taas muualla käytössä `TIMESTAMP WITH TIME ZONE` ? Liittyen `SchedulingConfig`:n  alla builderissa kutsuttuun `usingDbTime()` ?

2021-12-20 14:25 UTC, mikhuttu commented on src/main/java/fi/oph/akt/config/SchedulingConfig.java
> +@EnableSchedulerLock(defaultLockAtMostFor = "10m")
Toimiiko määritys 10m? Pitäisikö olla T10M ?

2021-12-20 14:25 UTC, mikhuttu commented on src/main/java/fi/oph/akt/repository/EmailRepository.java
> +	@Query("SELECT e.id FROM Email e WHERE e.sentAt IS NULL ORDER BY e.modifiedAt asc")
Voisi palauttaa Email-luokan instansseja

2021-12-20 14:25 UTC, mikhuttu commented on src/main/java/fi/oph/akt/repository/EmailRepository.java
> +import java.util.List;
Importin voi siirtää jos haluaa

2021-12-20 14:25 UTC, mikhuttu commented on src/main/java/fi/oph/akt/service/email/EmailScheduledSending.java
> +import fi.oph.akt.repository.EmailRepository;
Importit voi halutessa uudelleenjärjestää

2021-12-20 14:25 UTC, mikhuttu commented on src/main/java/fi/oph/akt/service/email/EmailScheduledSending.java
> +	// TODO Move constants to config?
Voidaan siirtää jo nyt tai sitten joskus myöhemmin tarvittaessa

2021-12-20 14:25 UTC, mikhuttu commented on src/main/java/fi/oph/akt/service/email/EmailScheduledSending.java
> +	@SchedulerLock(name = "pollEmailsToSend", lockAtLeastFor = FIXED_DELAY)
Pitäisikö asettaa eksplisiittisesti myös `lockAtMostFor` ?

2021-12-20 14:25 UTC, mikhuttu commented on src/main/java/fi/oph/akt/service/email/EmailScheduledSending.java
> +		final List<Long> emailsToSend = emailRepository.findEmailsToSend();
Voisi uudelleennimetä `emailsToSend --> emails` ja myös LOG.debug alla

2021-12-20 14:25 UTC, mikhuttu commented on src/main/java/fi/oph/akt/service/email/EmailScheduledSending.java
> +		emailsToSend.subList(0, Math.min(emailsToSend.size(), BATCH_SIZE)).forEach(emailService::sendEmail);
EmailService.sendEmail voisi ottaa `Email` luokan instanssin parameterina

2021-12-20 14:25 UTC, mikhuttu commented on src/main/java/fi/oph/akt/service/email/EmailService.java
> +	public Long saveEmail(final EmailData emailData) {
Metodi voisi muuten palauttaa tallennetun Emailin sen id:n sijaan, mutta tämä myös ok.

2021-12-20 14:25 UTC, mikhuttu commented on src/main/java/fi/oph/akt/service/email/EmailService.java
> +			email.setSentAt(LocalDateTime.now());
Tapahtuuko tämän yhteydessä automaattisesti myös update-operaation ajaminen tietokannassa ko. email-riville? Ts. jos tietokantatransaktiossa suoritetaan useampi setteri jo talletulle instanssille, jokainen niistä johtaa ilmeisesti yhteen update sql-ajoon?

2021-12-20 14:25 UTC, mikhuttu commented on src/main/java/fi/oph/akt/service/email/EmailService.java
> +		final Email email = emailRepository.getById(emailId);
Pitäisikö toteuttaa optionalin kautta `.findById`, jos emailia ei id:llä löydy?

2021-12-20 14:25 UTC, mikhuttu commented on src/main/java/fi/oph/akt/repository/EmailRepository.java
> +	@Query("SELECT e.id FROM Email e WHERE e.sentAt IS NULL ORDER BY e.modifiedAt asc")
Jos `error` kentän arvo ei ole null, pitäisikö ko. email hylätä tuloksista?

2021-12-20 14:25 UTC, mikhuttu commented on src/main/java/fi/oph/akt/service/email/sender/EmailSenderViestintapalvelu.java
> +			recipient.put("email", emailData.recipient());
Nämä (email ja recipient) voisi periaatteessa luoda ja palauttaa omissa alimetodeissaan

2021-12-20 14:25 UTC, mikhuttu commented on src/main/java/fi/oph/akt/service/email/sender/EmailSenderViestintapalvelu.java
> +			final WebClient webClient = WebClient.builder().baseUrl(emailServiceUrl)
Olisko tän hyvä olla staattinen muuttuja?

2021-12-20 14:25 UTC, mikhuttu commented on src/main/java/fi/oph/akt/service/email/EmailService.java
> +	public Long saveEmail(final EmailData emailData) {
Ja sellainen huomio vielä, että tä metodi voisi ottaa toisena parameterina `EmailType emailType`, jolloin meillä ei olisi tarve olla type-kenttää EmailDatan osana lainkaan.

2021-12-21 07:25 UTC, terova commented on src/main/resources/db/changelog/db.changelog-1.0.xml
> +    <changeSet id="2021-12-15-create-shedlock-table" author="terova">
Sillä ei ole oikeasti väliä mikä id on, mut, vaihdan.

2021-12-21 07:26 UTC, terova commented on src/main/resources/db/changelog/db.changelog-1.0.xml
> +                <constraints nullable="false" primaryKey="true"/>
shedlock changeset on heidän dokumentaatiosta copy paste.

2021-12-21 07:27 UTC, terova commented on src/main/java/fi/oph/akt/service/email/EmailService.java
> +			email.setSentAt(LocalDateTime.now());
Update ajetaan transaktion päättyessä niille entiteeteille joita on muutettu.

2021-12-21 07:28 UTC, terova commented on src/main/java/fi/oph/akt/service/email/sender/EmailSenderViestintapalvelu.java
> +			final WebClient webClient = WebClient.builder().baseUrl(emailServiceUrl)
Muutan niin että WebClient annetaan tähän ulkoa.

2021-12-21 07:30 UTC, terova commented on src/main/resources/db/changelog/db.changelog-1.0.xml
> +            <column name="locked_at" type="TIMESTAMP">
Tietotyypit sitä mitä ne shedlock dokumentaation linkkaamassa changesetissä on. usingDbTime tarkoittaa että kun lukko otetaan, käytetään tietokannan now() eikä kutsuvan sovelluksen aikaa.

2021-12-21 07:33 UTC, terova commented on src/main/java/fi/oph/akt/service/email/EmailService.java
> +		final Email email = emailRepository.getById(emailId);
Hyvä huomio, pitäisi.

2021-12-21 07:47 UTC, terova commented on src/main/resources/db/changelog/db.changelog-1.0.xml
> +            <column name="email_type" type="VARCHAR(255)">
Liquibasessa on afterColumn attribuutti columnille, mutta postgresql sellaista tue https://wiki.postgresql.org/wiki/Alter_column_position

2021-12-21 08:00 UTC, terova commented on src/main/java/fi/oph/akt/repository/EmailRepository.java
> +	@Query("SELECT e.id FROM Email e WHERE e.sentAt IS NULL ORDER BY e.modifiedAt asc")
Haetaan ne joita ei lähetetty, vanhiten muokatut ensin, yritetään lähettää, jos lähetys epäonnistuu merkitään error. Kun tätä kutsutaan uudestaan tulee epäonnistunut lähetys viimeisenä, ja kun kutsutaan uudestaan ja uudestaan tulee epäonnistunut lähetys uudestaan lähetettäväksi.

2021-12-21 08:04 UTC, terova commented on src/main/java/fi/oph/akt/service/email/EmailScheduledSending.java
> +		emailsToSend.subList(0, Math.min(emailsToSend.size(), BATCH_SIZE)).forEach(emailService::sendEmail);
Tässä on nuo transaktiorajat, ja jokainen sähköpostin lähetys yritetään omassa transaktiossaan. Saattaa toimia oikeanlaisilla entitymanagerin komentamisella että passattaisiin instansseja transaktiosta toiseen, mutta se aiheuttaa minulle kovin epämukavan olon. Kun välitetään id, on päivänselvää mitä pitää tehdä.

2021-12-21 13:41 UTC, mikhuttu reviewed
Kävin yllä olevat commitit läpi ja niiden ja aiemmin jättämieni kommenttien perusteella joitakin vielä alla.

2021-12-21 13:41 UTC, mikhuttu commented on pom.xml
> +			<artifactId>mockwebserver</artifactId>
Deprekoitu kirjasto? Voitanee tosin käyttää sillä ainakin siihen jokin alpha 5.0 versio kehitteillä nytkin.

2021-12-21 13:41 UTC, mikhuttu commented on src/main/java/fi/oph/akt/service/email/sender/EmailSenderNoOp.java
> +	public String sendEmail(EmailData emailData) {
`final` määreen voi lisätä takaisin

2021-12-21 13:41 UTC, mikhuttu commented on src/main/java/fi/oph/akt/service/email/sender/EmailSenderViestintapalvelu.java
> +		return map.get("id");
Kuten datan (tai sen osien) muodostamisen yltä, myös tämä voisi olla oma alimetodinsa `parseExternalId` tai vast. vaikka ei nyt sinänsä tarvetta kun sen verran pieni. `data` Mapin luonti voisi kyllä tapahtua ehkä omassa metodissa, kun tästä päämetodista nyt yli puolet vain datan muodostusta.

2021-12-21 13:41 UTC, mikhuttu commented on src/main/java/fi/oph/akt/repository/EmailRepository.java
>  @Repository
Voidaan lisätä myös muihin repositorioihin tämä annotaatio tämän PR:n yhteydessä

2021-12-21 13:41 UTC, mikhuttu commented on src/main/java/fi/oph/akt/service/email/EmailScheduledSending.java
> +	@SchedulerLock(name = "pollEmailsToSend", lockAtLeastFor = LOCK_AT_LEAST, lockAtMostFor = LOCK_AT_MOST)
Mulle `lockAtMostFor` asetus ei ollut alkuun lainkaan selvä. Mutta tämä taitaa olla siis konffattu olemaan 10 minuuttia (SchedulingConfig:n alta) jos sitä ei erikseen täällä asetettaisi? Silti ehkä hyvä että määritelty täällä eksplisiittisesti. Aikaa voisi toki miettiä että olisko hyvä olla vaikka puoli tuntia tai tunti? Tai sitten se default arvo uudelleenkirjoitettuna.

2021-12-21 13:41 UTC, mikhuttu commented on src/main/java/fi/oph/akt/service/email/EmailService.java
> +			LOG.error("Exception when sending email", e);
Tässä vois lokittaa myös emailin id:n jota yritettiin lähettää

2021-12-21 13:41 UTC, mikhuttu commented on src/main/resources/oph-configuration/akt.properties.template
> +email.sending.enabled=true
Nämä voi halutessa vaihtaa päittäin jotta oisivat määritelty samassa järjestyksessä kuin application.yaml:ssa. Toistaiseksi ei mitään väliä mut jos konffeja olis paljon niin ois kätsy.

2021-12-21 13:41 UTC, mikhuttu commented on src/main/resources/application.yaml
> +    ryhmasahkoposti-service-url: ${ryhmasahkoposti-service:null}
`ryhmasahkoposti-service` --> `email.ryhmasahkoposti-service-url`

2021-12-21 13:41 UTC, mikhuttu commented on src/main/resources/application.yaml
> +    sending-enabled: ${email.sending.enabled:false}
email.sending.enabled --> email.sending-enabled

2021-12-21 13:41 UTC, mikhuttu commented on src/main/java/fi/oph/akt/service/email/EmailService.java
> +		emailData.copyToEmail(email);
Voisi ehkä asettaa emailin kaikkien kenttien arvot tässä metodissa ja poistaa tuon `copyToEmail` metodin

2021-12-21 14:38 UTC, terova commented on src/main/java/fi/oph/akt/repository/EmailRepository.java
>  @Repository
Jännä että edes toimivat ilman.

2021-12-21 14:41 UTC, mikhuttu reviewed
Kattavia ja hyviä testejä 👍

2021-12-21 14:41 UTC, mikhuttu commented on src/test/java/fi/oph/akt/service/email/EmailServiceTest.java
> +	public void testMailIsSaved() throws JsonProcessingException {
`throws JsonProcessingException` voi poistaa. Testin voisi myös uudelleennimetä `saveEmailTest`

2021-12-21 14:41 UTC, mikhuttu commented on src/main/java/fi/oph/akt/model/Email.java
> +	@Column(name = "ext_id", nullable = false)
`nullable = false` tarkoitus varmaan poistaa

2021-12-21 14:41 UTC, mikhuttu commented on src/test/java/fi/oph/akt/service/email/EmailServiceTest.java
> +		assertNull(persistedEmail.getSentAt());
emailTypen voisi vielä tarkistaa

2021-12-21 14:41 UTC, mikhuttu commented on src/test/java/fi/oph/akt/service/email/EmailServiceTest.java
> +	public void testMailIsSent() throws JsonProcessingException {
`sendEmailSuccessTest` ?

2021-12-21 14:41 UTC, mikhuttu commented on src/test/java/fi/oph/akt/service/email/EmailServiceTest.java
> +	public void testMailSendingFailed() throws JsonProcessingException {
`sendEmailFailureTest` ?

2021-12-21 14:41 UTC, mikhuttu commented on src/test/java/fi/oph/akt/service/email/EmailServiceTest.java
> +
Jos haluat niin voit lisätä testin, joka varmistaa että lähetys ei aiheuta virhetilannetta, jos emailia annetulla id:llä ei löydy.

2021-12-21 14:41 UTC, mikhuttu commented on src/test/java/fi/oph/akt/service/email/EmailScheduledSendingTest.java
> +	public void testSendEmails() {
`pollEmailsToSendSendsOnlyUnsentEmails`

2021-12-21 14:41 UTC, mikhuttu commented on src/test/java/fi/oph/akt/service/email/sender/EmailSenderViestintapalveluTest.java
> +import static junit.framework.TestCase.assertEquals;
Korvataan tällä `import static org.junit.jupiter.api.Assertions.assertEquals;`

2021-12-21 14:41 UTC, mikhuttu commented on src/test/java/fi/oph/akt/service/email/sender/EmailSenderViestintapalveluTest.java
> +		final String senderId = sender.sendEmail(emailData);
Voisi uudelleenimetä `id` tai `extId`

2021-12-21 17:17 UTC, terova commented on src/main/java/fi/oph/akt/service/email/EmailScheduledSending.java
> +	@SchedulerLock(name = "pollEmailsToSend", lockAtLeastFor = LOCK_AT_LEAST, lockAtMostFor = LOCK_AT_MOST)
Näillä asetuksilla yritetään kerrallaan lähettää 10 sähköpostia. Jos jostakin syystä jokaisen lähettämiseen menee minuutti, ei tuo 10 minuuttia riitä. Pääasia lockAtMostFor tässä sähköpostin tapauksessa on että jos tuo lukko jää, se itsekseen vapautuu. Ei ole niin paljoa väliä kuinka kauan vapauttamiseen menee, jotta joku toinen pääsee sitten lähettämään, koska näillä sähköposteilla ei ole mikään kiire.

2021-12-22 07:04 UTC, mikhuttu approved these changes

2021-12-22 07:05 UTC, merged