Feature/ophaktkeh 129
Opetushallitus/akt pull request #70
Opened 2021-12-31 14:55 UTC by mikhuttu

Toteutus virkailijapuolen kääntäjälistauksesta, joka palauttaa rajapinnan kuvaamaa dataa: https://wiki.eduuni.fi/display/OPHPALV/Virkailijarajapinnat

Täältä puuttuu nyt ainakin junit-testit ennen kuin pull requestia voi avata, mutta muutoin päällisin puolin tässä.

2022-01-04 12:57 UTC, pkoivisto reviewed
Näyttää mun mielestä ihan asialliselta, ja APIn kautta palautettava data kanssa vaikuttaa nopean testin perusteella siltä mitä pitääkin. Ainoa kysymys mikä heräsi (kommentoin tästä myös wikin puolelle) oli että pitäisikö ClerkTranslatorDTOn lisätä kenttä kääntäjän lisätiedoille.

Koodikäytäntöjen osalta varmaan ihan hyvä että myös joku meidän Java-bäkkäriä enemmän työstänyt katselmoisi, mutta omaan silmääni oli ihan luettavaa koodia. 👍

2022-01-04 15:11 UTC, terova requested changes

2022-01-04 15:11 UTC, terova commented on src/main/java/fi/oph/akt/api/dto/clerk/ClerkTranslatorContactDetailsDTO.java
> +		String phoneNumber, String identityNumber, String street, String postalCode, String city, String town) {
city ja town on epäselvää mitä ne ovat. Jos toinen on asuinkunta, niin kuinka se eroaa postiosoitteen kunnasta? Mielestäni ei mitenkään, asuinkunta on osoitteen kunta.

2022-01-04 15:11 UTC, terova commented on src/main/java/fi/oph/akt/repository/AuthorisationRepository.java
> +	List<TranslatorAuthorisationProjection> findAuthorisationsByTranslators(Iterable<Long> translatorIds);
Tämä on sellainen pieni optimointi mitä olen miettinyt: jos kerta kaikki haetaan, ei id listalla tarvitse hakea, nopeuttaa vähän ja yksinkertaistaa.

2022-01-04 15:11 UTC, terova commented on src/main/java/fi/oph/akt/repository/AuthorisationTermRepository.java
> +	List<AuthorisationTermProjection> findTermsByAuthorisations(Iterable<Long> authorisationIds);
Sama juttu: jos kaikki haetaan mihin id listaa tarvitaan.

2022-01-04 15:11 UTC, terova commented on src/main/java/fi/oph/akt/service/ClerkTranslatorService.java
>  public class ClerkTranslatorService {
Voiko tällekin laittaa RequiredArgsConstructor ?

2022-01-04 17:35 UTC, mikhuttu commented
> 

Juteltiin eilen Niklaksen kanssa juuri noista kääntäjän lisätiedoista. Niiden funktio taisi alun perin olla se, että OPH:n virkailijat voisivat kirjata ylös, miten kääntäjän tietoja on ajan saatossa muutettu. Jos tuo tosin jäisi puhtaasti meidän audit lokin varaan ja tällaiselle manuaalisesti ylläpidettävälle sisällölle ei ole tarvetta, niin jäisi kokonaan sellainen pois. Pitää tosin jutella vielä weeklyssä, että voidaanko tuo jättää pois.

2022-01-04 17:37 UTC, mikhuttu commented on src/main/java/fi/oph/akt/api/dto/clerk/ClerkTranslatorContactDetailsDTO.java
> +		String phoneNumber, String identityNumber, String street, String postalCode, String city, String town) {
Pohdin tuota myös että onko meillä tarve erotella postiosoitteen kuntaa ja asuinkuntaa, kun oletettavasti ovat samat kaikille kääntäjille. Toisaalta jos joku on kirjoilla toisessa paikassa, mutta tekee pääosin työtä toisen kunnan alueella?

2022-01-04 17:55 UTC, mikhuttu commented on src/main/java/fi/oph/akt/service/ClerkTranslatorService.java
>  public class ClerkTranslatorService {
Toteutettu ophaktkeh-133 pull requestissa jonka katselmoitkin myös

2022-01-05 07:38 UTC, terova approved these changes

2022-01-05 09:06 UTC, terova commented on src/main/java/fi/oph/akt/onr/OnrServiceMock.java
> +	private final Iterator<String> countries = cyclicIter("Suomi", "suomi", "SUOMI", "Finland", "FINLAND", "Latvia");
Mutta voihan se olla kannassa tyhjä tai null.

2022-01-05 09:08 UTC, mikhuttu commented on src/main/java/fi/oph/akt/onr/OnrServiceMock.java
> +	private final Iterator<String> countries = cyclicIter("Suomi", "suomi", "SUOMI", "Finland", "FINLAND", "Latvia");
Joo, mä ajattelin tän nyt väärin @pkoivisto pull requestin mukaan. Kaikki kentäthän contactDetails modelissa pl. firstName ja lastName voi olla null.

2022-01-05 09:08 UTC, mikhuttu commented on src/main/java/fi/oph/akt/onr/OnrServiceMock.java
> +	private final Iterator<String> countries = cyclicIter("Suomi", "suomi", "SUOMI", "Finland", "FINLAND", "Latvia");
Poistan yo. commitin.

2022-01-05 09:29 UTC, terova approved these changes

2022-01-05 09:30 UTC, merged